name: Coverage (stub)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate stub
    runs-on: ubuntu-latest
    steps:
      - name: Echo stub
        run: echo "coverage stub ok"
