name: Coverage (tests only)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Checkout / Install / Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust 1.90.0
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.90.0

      - name: Enable cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Prefetch dependencies (locked)
        run: cargo fetch --locked

      - name: Run tests (locked)
        run: cargo test --locked
