name: E2E (MCP Inspector)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    name: Inspector tools/list
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.90.0
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Lint (clippy)
        run: cargo clippy --all-targets -- -D warnings
      - name: Build (release)
        run: cargo build --release --locked
      - name: Inspector initialize (preflight)
        timeout-minutes: 10
        run: |
          npm -g i @modelcontextprotocol/inspector-cli@latest
          export MCP_DIAG_LOG="$GITHUB_WORKSPACE/mcp-diag.log"
          # Some inspector versions support --timeout-ms; tolerate if unsupported by defaulting
          npx @modelcontextprotocol/inspector-cli --cli ./target/release/github-mcp --method initialize --timeout-ms 30000 > out-init.json || npx @modelcontextprotocol/inspector-cli --cli ./target/release/github-mcp --method initialize > out-init.json
          if [ -f out-init.json ]; then cat out-init.json; else echo "out-init.json missing"; fi
          node -e 'const o=require("./out-init.json"); if(!o.result||o.result.protocolVersion!=="2024-11-05"||!o.result.serverInfo||!o.result.capabilities){console.error("initialize response invalid"); process.exit(1)}'

      - name: Inspector tools/list
        timeout-minutes: 10
        run: |
          export MCP_DIAG_LOG="$GITHUB_WORKSPACE/mcp-diag.log"
          npx @modelcontextprotocol/inspector-cli --cli ./target/release/github-mcp --method tools/list --timeout-ms 30000 > out-tools.json || npx @modelcontextprotocol/inspector-cli --cli ./target/release/github-mcp --method tools/list > out-tools.json
          if [ -f out-tools.json ]; then cat out-tools.json; else echo "out-tools.json missing"; fi
          node -e 'const o=require("./out-tools.json"); if(!o.result||!Array.isArray(o.result.tools)||!o.result.tools.find(t=>t.name==="ping")){console.error("ping tool missing"); process.exit(1)}'
      - name: Smoke stdio LF-only
        run: |
          node ./scripts/smoke_stdio_lf.js ./target/release/github-mcp
      - name: Upload MCP diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mcp-diag
          path: |
            mcp-diag.log
            diag-smoke.log
            out-init.json
            out-tools.json
