name: Release Please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          package-name: github-mcp
          bump-minor-pre-major: true
